language: node_js

node_js:
  - 14

services:
  - postgresql

install:
  - yarn install

before_script:
  - psql -c "create database gourmet_test;" -U postgres

script:
  - yarn test

notification:
  - email: false
